Repository stolostron/lifeguard, pull requests merged in 2021-02, with the labels that each got.

#21 Use version sorting for images
  clusterpools/apply.sh
Labels: lgtm

#23 Update logic to allow more clusters
  clusterclaims/apply.sh
Labels: lgtm

#24 Adding a license, owners, and security file
  LICENSE
  OWNERS
  SECURITY.md
Labels: lgtm

#20 Make oc-login.sh executable
  clusterclaims/get_credentials.sh
Labels: approved, lgtm

#18 Check for True conditions, since conditions may not be present if False
  clusterclaims/apply.sh
  clusterclaims/get_credentials.sh
Labels: approved, dco-signoff: no, lgtm

#22 Add ability to create pool with claim
  clusterclaims/apply.sh
Labels: approved, lgtm

#19 Always use errorf before non-zero exits
  clusterclaims/apply.sh
  clusterclaims/delete.sh
  clusterclaims/get_credentials.sh
  clusterclaims/reconcile_claims.sh
  clusterpools/apply.sh
  clusterpools/delete.sh
Labels: approved, lgtm

#25 Add option to reconcile silently
  README.md
  clusterclaims/reconcile_claims.sh
Labels: approved, lgtm
